### ISSUE TITLE
Is it possible to change default launch url

### ISSUE THREAD

**Issue by jasonhemu** [asheshv/pgadmin4#4]
Hi there,

I am trying to deploy the pgadmin4 on my server via docker. Is it possible to launch the program from example.com/pgadmin instead of example.com? I tried to edit the config.py, but did not success. Here is my docker-compose.yml. Any advice would be really appreciated!

```
pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./setupfiles/pgadmin_config.py:/pgadmin4/config.py
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.frontend.rule=Host:${TRAEFIK_DOMAINS}; PathPrefixStrip:/pgadmin
      - traefik.port=80
      - traefik.backend=pgadmin
```
